adminUser:
  password: vault:jx-aps-gargoylecrimson/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-gargoylecrimson:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-gargoylecrimson:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-gargoylecrimson/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-gargoylecrimson/prow:hmacToken
